#FILE:femaleFirstNames.t 
4:<~alban-f.t>
4:<~arabic-f.t>
4:<~armenia-f.t>
4:<~austria-f.t>
4:<~belgium-f.t>
4:<~czech-f.t>
4:<~danish-f.t>
4:<~dutch-f.t>
4:<~en-f.t>
4:<~finnish-f.t>
4:<~fr-f.t>
4:<~ge-f.t>
4:<~gr-f.t>
4:<~hungary-f.t>
4:<~iceland-f.t>
4:<~italian-f.t>
4:<~niger-f.t>
4:<~norway-f.t>
4:<~pole-f.t>
4:<~portug-f.t>
4:<~russian-f.t>
4:<~spanish-f.t>
4:<~swedish-f.t>
4:<~swiss-f.t>
#IMPORT:alban-f.t
#IMPORT:arabic-f.t
#IMPORT:armenia-f.t
#IMPORT:austria-f.t
#IMPORT:belgium-f.t
#IMPORT:czech-f.t
#IMPORT:danish-f.t
#IMPORT:dutch-f.t
#IMPORT:en-f.t
#IMPORT:finnish-f.t
#IMPORT:fr-f.t
#IMPORT:ge-f.t
#IMPORT:gr-f.t
#IMPORT:hungary-f.t
#IMPORT:iceland-f.t
#IMPORT:italian-f.t
#IMPORT:niger-f.t
#IMPORT:norway-f.t
#IMPORT:pole-f.t
#IMPORT:portug-f.t
#IMPORT:russian-f.t
#IMPORT:spanish-f.t
#IMPORT:swedish-f.t
#IMPORT:swiss-f.t
