#FILE:maleFirstNames.t 
4:<~alban-m.t>
4:<~arabic-m.t>
4:<~armenia-m.t>
4:<~austria-m.t>
4:<~belgium-m.t>
4:<~czech-m.t>
4:<~danish-m.t>
4:<~dutch-m.t>
4:<~en-m.t>
4:<~finnish-m.t>
4:<~fr-m.t>
4:<~ge-m.t>
4:<~gr-m.t>
4:<~hungary-m.t>
4:<~iceland-m.t>
4:<~italian-m.t>
4:<~niger-m.t>
4:<~norway-m.t>
4:<~pole-m.t>
4:<~portug-m.t>
4:<~russian-m.t>
4:<~spanish-m.t>
4:<~swedish-m.t>
4:<~swiss-m.t>
#IMPORT:alban-m.t
#IMPORT:arabic-m.t
#IMPORT:armenia-m.t
#IMPORT:austria-m.t
#IMPORT:belgium-m.t
#IMPORT:czech-m.t
#IMPORT:danish-m.t
#IMPORT:dutch-m.t
#IMPORT:finnish-m.t
#IMPORT:fr-m.t
#IMPORT:ge-m.t
#IMPORT:gr-m.t
#IMPORT:hungary-m.t
#IMPORT:iceland-m.t
#IMPORT:italian-m.t
#IMPORT:niger-m.t
#IMPORT:norway-m.t
#IMPORT:pole-m.t
#IMPORT:portug-m.t
#IMPORT:russian-m.t
#IMPORT:spanish-m.t
#IMPORT:swedish-m.t
#IMPORT:swiss-m.t
