#FILE:names.t
1:alban,Albanian
1:arabic,Arabic
1:armenia,Armenian
1:austria,Austrian
1:belgium,Belgin
1:czech,Czech
1:danish,Danish
1:dutch,Dutch
1:finnish,Finnish
1:fr,French
1:ge,German
1:gr,Greek
1:hungary,Hungarian
1:iceland,Icelandic
1:italian,Italian
1:niger,Nigerian
1:norway,Norwegian
1:pole,Polish
1:portug,Portuguese
1:russian,Russian
1:spanish,Spanish
1:swedish,Swedish
1:swiss,Swiss